name: spider-check
on:
  # Once a week on Friday at 00:00
  schedule:
    - cron: '0 0 * * 5'
  # Or manually
  workflow_dispatch:
  # Or when developing this workflow
  push:
    paths:
      - .github/workflows/spider-check.yaml
      - .github/configs/hydra-config.json
  pull_request:
    paths:
      - .github/workflows/spider-check.yaml
      - .github/configs/hydra-config.json

jobs:
  spider-check:
    if: ${{ github.repository_owner == 'jquery' }} # skip on forks
    runs-on: ubuntu-latest
    env:
      # Site address to crawl
      MY_SITE: https://api.jquery.com
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run hydra-link-checker
        run: |
          curl -O https://raw.githubusercontent.com/jquery/hydra-link-checker/v2.0.0/hydra.py
          python3 hydra.py "$MY_SITE" --config .github/configs/hydra-config.json
